
connect_debug_port u_ila_0/probe0 [get_nets [list {nolabel_line10/ram_rxd[0]} {nolabel_line10/ram_rxd[1]} {nolabel_line10/ram_rxd[2]} {nolabel_line10/ram_rxd[3]} {nolabel_line10/ram_rxd[4]} {nolabel_line10/ram_rxd[5]} {nolabel_line10/ram_rxd[6]} {nolabel_line10/ram_rxd[7]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {nolabel_line10/rx_ram_txd[0]} {nolabel_line10/rx_ram_txd[1]} {nolabel_line10/rx_ram_txd[2]} {nolabel_line10/rx_ram_txd[3]} {nolabel_line10/rx_ram_txd[4]} {nolabel_line10/rx_ram_txd[5]} {nolabel_line10/rx_ram_txd[6]} {nolabel_line10/rx_ram_txd[7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {nolabel_line10/com_rxd[0]} {nolabel_line10/com_rxd[1]} {nolabel_line10/com_rxd[2]} {nolabel_line10/com_rxd[3]} {nolabel_line10/com_rxd[4]} {nolabel_line10/com_rxd[5]} {nolabel_line10/com_rxd[6]} {nolabel_line10/com_rxd[7]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {nolabel_line10/ram_txd[0]} {nolabel_line10/ram_txd[1]} {nolabel_line10/ram_txd[2]} {nolabel_line10/ram_txd[3]} {nolabel_line10/ram_txd[4]} {nolabel_line10/ram_txd[5]} {nolabel_line10/ram_txd[6]} {nolabel_line10/ram_txd[7]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {nolabel_line10/ram_txa[0]} {nolabel_line10/ram_txa[1]} {nolabel_line10/ram_txa[2]} {nolabel_line10/ram_txa[3]} {nolabel_line10/ram_txa[4]} {nolabel_line10/ram_txa[5]} {nolabel_line10/ram_txa[6]} {nolabel_line10/ram_txa[7]} {nolabel_line10/ram_txa[8]} {nolabel_line10/ram_txa[9]} {nolabel_line10/ram_txa[10]} {nolabel_line10/ram_txa[11]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {nolabel_line10/rx_bdata[0]} {nolabel_line10/rx_bdata[1]} {nolabel_line10/rx_bdata[2]} {nolabel_line10/rx_bdata[3]} {nolabel_line10/rx_bdata[4]} {nolabel_line10/rx_bdata[5]} {nolabel_line10/rx_bdata[6]} {nolabel_line10/rx_bdata[7]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {nolabel_line10/rx_btype[0]} {nolabel_line10/rx_btype[1]} {nolabel_line10/rx_btype[2]} {nolabel_line10/rx_btype[3]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {nolabel_line10/rx_didx[0]} {nolabel_line10/rx_didx[1]} {nolabel_line10/rx_didx[2]} {nolabel_line10/rx_didx[3]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {nolabel_line10/btype[0]} {nolabel_line10/btype[1]} {nolabel_line10/btype[2]} {nolabel_line10/btype[3]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {nolabel_line10/ram_rxa[0]} {nolabel_line10/ram_rxa[1]} {nolabel_line10/ram_rxa[2]} {nolabel_line10/ram_rxa[3]} {nolabel_line10/ram_rxa[4]} {nolabel_line10/ram_rxa[5]} {nolabel_line10/ram_rxa[6]} {nolabel_line10/ram_rxa[7]} {nolabel_line10/ram_rxa[8]} {nolabel_line10/ram_rxa[9]} {nolabel_line10/ram_rxa[10]} {nolabel_line10/ram_rxa[11]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list nolabel_line10/fd_ram_tx]]
connect_debug_port u_ila_0/probe13 [get_nets [list nolabel_line10/fd_rx]]
connect_debug_port u_ila_0/probe14 [get_nets [list nolabel_line10/fd_typec_tx]]
connect_debug_port u_ila_0/probe15 [get_nets [list nolabel_line10/fs_ram_tx]]
connect_debug_port u_ila_0/probe16 [get_nets [list nolabel_line10/fs_rx]]
connect_debug_port u_ila_0/probe17 [get_nets [list nolabel_line10/fs_typec_tx]]
connect_debug_port u_ila_0/probe18 [get_nets [list nolabel_line10/ram_txen]]



connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
connect_debug_port u_ila_0/probe0 [get_nets [list {nolabel_line10/state[0]} {nolabel_line10/state[1]} {nolabel_line10/state[2]} {nolabel_line10/state[3]} {nolabel_line10/state[4]} {nolabel_line10/state[5]} {nolabel_line10/state[6]} {nolabel_line10/state[7]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {nolabel_line10/rx_bdata[0]} {nolabel_line10/rx_bdata[1]} {nolabel_line10/rx_bdata[2]} {nolabel_line10/rx_bdata[3]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {nolabel_line10/rx_btype[0]} {nolabel_line10/rx_btype[1]} {nolabel_line10/rx_btype[2]} {nolabel_line10/rx_btype[3]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {nolabel_line10/tx_btype[0]} {nolabel_line10/tx_btype[1]} {nolabel_line10/tx_btype[2]} {nolabel_line10/tx_btype[3]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {nolabel_line10/typec_rx_dut/state[0]} {nolabel_line10/typec_rx_dut/state[1]} {nolabel_line10/typec_rx_dut/state[2]} {nolabel_line10/typec_rx_dut/state[3]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {nolabel_line10/com_txd[0]} {nolabel_line10/com_txd[1]} {nolabel_line10/com_txd[2]} {nolabel_line10/com_txd[3]} {nolabel_line10/com_txd[4]} {nolabel_line10/com_txd[5]} {nolabel_line10/com_txd[6]} {nolabel_line10/com_txd[7]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list nolabel_line10/fd_rx]]
connect_debug_port u_ila_0/probe7 [get_nets [list nolabel_line10/fd_tx]]
connect_debug_port u_ila_0/probe8 [get_nets [list nolabel_line10/fs_rx]]
connect_debug_port u_ila_0/probe9 [get_nets [list nolabel_line10/fs_tx]]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]

connect_debug_port u_ila_0/clk [get_nets [list tb_typec_txf_dut/mmcm_dut/inst/clk_out2]]
connect_debug_port u_ila_0/probe0 [get_nets [list {tb_typec_txf_dut/com_txd[0]} {tb_typec_txf_dut/com_txd[1]} {tb_typec_txf_dut/com_txd[2]} {tb_typec_txf_dut/com_txd[3]} {tb_typec_txf_dut/com_txd[4]} {tb_typec_txf_dut/com_txd[5]} {tb_typec_txf_dut/com_txd[6]} {tb_typec_txf_dut/com_txd[7]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {tb_typec_txf_dut/com_rxd[0]} {tb_typec_txf_dut/com_rxd[1]} {tb_typec_txf_dut/com_rxd[2]} {tb_typec_txf_dut/com_rxd[3]} {tb_typec_txf_dut/com_rxd[4]} {tb_typec_txf_dut/com_rxd[5]} {tb_typec_txf_dut/com_rxd[6]} {tb_typec_txf_dut/com_rxd[7]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {tb_typec_txf_dut/rx_didx[0]} {tb_typec_txf_dut/rx_didx[1]} {tb_typec_txf_dut/rx_didx[2]} {tb_typec_txf_dut/rx_didx[3]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {tb_typec_txf_dut/btype[0]} {tb_typec_txf_dut/btype[1]} {tb_typec_txf_dut/btype[2]} {tb_typec_txf_dut/btype[3]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {tb_typec_txf_dut/rx_btype[0]} {tb_typec_txf_dut/rx_btype[1]} {tb_typec_txf_dut/rx_btype[2]} {tb_typec_txf_dut/rx_btype[3]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {tb_typec_txf_dut/rx_ram_txd[0]} {tb_typec_txf_dut/rx_ram_txd[1]} {tb_typec_txf_dut/rx_ram_txd[2]} {tb_typec_txf_dut/rx_ram_txd[3]} {tb_typec_txf_dut/rx_ram_txd[4]} {tb_typec_txf_dut/rx_ram_txd[5]} {tb_typec_txf_dut/rx_ram_txd[6]} {tb_typec_txf_dut/rx_ram_txd[7]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {tb_typec_txf_dut/state[0]} {tb_typec_txf_dut/state[1]} {tb_typec_txf_dut/state[2]} {tb_typec_txf_dut/state[3]} {tb_typec_txf_dut/state[4]} {tb_typec_txf_dut/state[5]} {tb_typec_txf_dut/state[6]} {tb_typec_txf_dut/state[7]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {tb_typec_txf_dut/ram_rxa[0]} {tb_typec_txf_dut/ram_rxa[1]} {tb_typec_txf_dut/ram_rxa[2]} {tb_typec_txf_dut/ram_rxa[3]} {tb_typec_txf_dut/ram_rxa[4]} {tb_typec_txf_dut/ram_rxa[5]} {tb_typec_txf_dut/ram_rxa[6]} {tb_typec_txf_dut/ram_rxa[7]} {tb_typec_txf_dut/ram_rxa[8]} {tb_typec_txf_dut/ram_rxa[9]} {tb_typec_txf_dut/ram_rxa[10]} {tb_typec_txf_dut/ram_rxa[11]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {tb_typec_txf_dut/ram_txa[0]} {tb_typec_txf_dut/ram_txa[1]} {tb_typec_txf_dut/ram_txa[2]} {tb_typec_txf_dut/ram_txa[3]} {tb_typec_txf_dut/ram_txa[4]} {tb_typec_txf_dut/ram_txa[5]} {tb_typec_txf_dut/ram_txa[6]} {tb_typec_txf_dut/ram_txa[7]} {tb_typec_txf_dut/ram_txa[8]} {tb_typec_txf_dut/ram_txa[9]} {tb_typec_txf_dut/ram_txa[10]} {tb_typec_txf_dut/ram_txa[11]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {tb_typec_txf_dut/rx_bdata[0]} {tb_typec_txf_dut/rx_bdata[1]} {tb_typec_txf_dut/rx_bdata[2]} {tb_typec_txf_dut/rx_bdata[3]} {tb_typec_txf_dut/rx_bdata[4]} {tb_typec_txf_dut/rx_bdata[5]} {tb_typec_txf_dut/rx_bdata[6]} {tb_typec_txf_dut/rx_bdata[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {tb_typec_txf_dut/pin[0]} {tb_typec_txf_dut/pin[1]} {tb_typec_txf_dut/pin[2]} {tb_typec_txf_dut/pin[3]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {tb_typec_txf_dut/ram_rxd[0]} {tb_typec_txf_dut/ram_rxd[1]} {tb_typec_txf_dut/ram_rxd[2]} {tb_typec_txf_dut/ram_rxd[3]} {tb_typec_txf_dut/ram_rxd[4]} {tb_typec_txf_dut/ram_rxd[5]} {tb_typec_txf_dut/ram_rxd[6]} {tb_typec_txf_dut/ram_rxd[7]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {tb_typec_txf_dut/ram_txd[0]} {tb_typec_txf_dut/ram_txd[1]} {tb_typec_txf_dut/ram_txd[2]} {tb_typec_txf_dut/ram_txd[3]} {tb_typec_txf_dut/ram_txd[4]} {tb_typec_txf_dut/ram_txd[5]} {tb_typec_txf_dut/ram_txd[6]} {tb_typec_txf_dut/ram_txd[7]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list tb_typec_txf_dut/fd_ram_tx]]
connect_debug_port u_ila_0/probe14 [get_nets [list tb_typec_txf_dut/fd_rx]]
connect_debug_port u_ila_0/probe15 [get_nets [list tb_typec_txf_dut/fd_typec_tx]]
connect_debug_port u_ila_0/probe16 [get_nets [list tb_typec_txf_dut/fire]]
connect_debug_port u_ila_0/probe17 [get_nets [list tb_typec_txf_dut/fs_ram_tx]]
connect_debug_port u_ila_0/probe18 [get_nets [list tb_typec_txf_dut/fs_rx]]
connect_debug_port u_ila_0/probe19 [get_nets [list tb_typec_txf_dut/fs_typec_tx]]
connect_debug_port u_ila_0/probe20 [get_nets [list tb_typec_txf_dut/ram_txen]]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out2]



connect_debug_port u_ila_0/clk [get_nets [list tb_typec_rxf_dut/mmcm_dut/inst/clk_out3]]
connect_debug_port u_ila_0/probe0 [get_nets [list {tb_typec_rxf_dut/typec_rxf_dut/state[0]} {tb_typec_rxf_dut/typec_rxf_dut/state[1]} {tb_typec_rxf_dut/typec_rxf_dut/state[2]} {tb_typec_rxf_dut/typec_rxf_dut/state[3]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {tb_typec_rxf_dut/typecm_txf_dut/state[0]} {tb_typec_rxf_dut/typecm_txf_dut/state[1]} {tb_typec_rxf_dut/typecm_txf_dut/state[2]} {tb_typec_rxf_dut/typecm_txf_dut/state[3]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {tb_typec_rxf_dut/com_rxd[0]} {tb_typec_rxf_dut/com_rxd[1]} {tb_typec_rxf_dut/com_rxd[2]} {tb_typec_rxf_dut/com_rxd[3]} {tb_typec_rxf_dut/com_rxd[4]} {tb_typec_rxf_dut/com_rxd[5]} {tb_typec_rxf_dut/com_rxd[6]} {tb_typec_rxf_dut/com_rxd[7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {tb_typec_rxf_dut/com_txd[0]} {tb_typec_rxf_dut/com_txd[1]} {tb_typec_rxf_dut/com_txd[2]} {tb_typec_rxf_dut/com_txd[3]} {tb_typec_rxf_dut/com_txd[4]} {tb_typec_rxf_dut/com_txd[5]} {tb_typec_rxf_dut/com_txd[6]} {tb_typec_rxf_dut/com_txd[7]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list tb_typec_rxf_dut/fire]]
connect_debug_port u_ila_0/probe5 [get_nets [list tb_typec_rxf_dut/pin]]
connect_debug_port u_ila_1/clk [get_nets [list tb_typec_rxf_dut/mmcm_dut/inst/clk_out1]]
connect_debug_port u_ila_1/probe0 [get_nets [list {tb_typec_rxf_dut/typec_rx_dut/state[0]} {tb_typec_rxf_dut/typec_rx_dut/state[1]} {tb_typec_rxf_dut/typec_rx_dut/state[2]} {tb_typec_rxf_dut/typec_rx_dut/state[3]}]]
connect_debug_port u_ila_1/probe1 [get_nets [list {tb_typec_rxf_dut/state[0]} {tb_typec_rxf_dut/state[1]} {tb_typec_rxf_dut/state[2]} {tb_typec_rxf_dut/state[3]} {tb_typec_rxf_dut/state[4]} {tb_typec_rxf_dut/state[5]} {tb_typec_rxf_dut/state[6]} {tb_typec_rxf_dut/state[7]}]]
connect_debug_port u_ila_1/probe2 [get_nets [list {tb_typec_rxf_dut/rx_bdata[0]} {tb_typec_rxf_dut/rx_bdata[1]} {tb_typec_rxf_dut/rx_bdata[2]} {tb_typec_rxf_dut/rx_bdata[3]}]]
connect_debug_port u_ila_1/probe3 [get_nets [list {tb_typec_rxf_dut/tx_btype[0]} {tb_typec_rxf_dut/tx_btype[1]} {tb_typec_rxf_dut/tx_btype[2]} {tb_typec_rxf_dut/tx_btype[3]}]]
connect_debug_port u_ila_1/probe4 [get_nets [list {tb_typec_rxf_dut/rx_btype[0]} {tb_typec_rxf_dut/rx_btype[1]} {tb_typec_rxf_dut/rx_btype[2]} {tb_typec_rxf_dut/rx_btype[3]}]]
connect_debug_port u_ila_1/probe5 [get_nets [list tb_typec_rxf_dut/fd_rx]]
connect_debug_port u_ila_1/probe6 [get_nets [list tb_typec_rxf_dut/fd_tx]]
connect_debug_port u_ila_1/probe7 [get_nets [list tb_typec_rxf_dut/fs_rx]]
connect_debug_port u_ila_1/probe8 [get_nets [list tb_typec_rxf_dut/fs_tx]]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clk_out1]

connect_debug_port u_ila_0/probe11 [get_nets [list {tb_typec_dut/pm_cc[0]} {tb_typec_dut/pm_cc[1]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {tb_typec_dut/ps_cc[0]} {tb_typec_dut/ps_cc[1]}]]

connect_debug_port u_ila_0/probe4 [get_nets [list {tb_typec_dut/ps_sbu[0]} {tb_typec_dut/ps_sbu[1]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {tb_typec_dut/pm_sbu[0]} {tb_typec_dut/pm_sbu[1]}]]

connect_debug_port u_ila_0/probe0 [get_nets [list {tb_typec_dut/typec_dut/typec_rxf_dut/state[0]} {tb_typec_dut/typec_dut/typec_rxf_dut/state[1]} {tb_typec_dut/typec_dut/typec_rxf_dut/state[2]} {tb_typec_dut/typec_dut/typec_rxf_dut/state[3]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {tb_typec_dut/typecm_dut/typecm_txf_dut/state[0]} {tb_typec_dut/typecm_dut/typecm_txf_dut/state[1]} {tb_typec_dut/typecm_dut/typecm_txf_dut/state[2]} {tb_typec_dut/typecm_dut/typecm_txf_dut/state[3]}]]
connect_debug_port u_ila_0/probe25 [get_nets [list tb_typec_dut/ps_rxd]]

connect_debug_port u_ila_0/probe7 [get_nets [list {tb_typec_dut/ps_rxd[0]} {tb_typec_dut/ps_rxd[1]}]]

connect_debug_port u_ila_0/clk [get_nets [list tb_typec_dut/mmcm_dut/inst/clk_out3]]
connect_debug_port u_ila_0/probe0 [get_nets [list {tb_typec_dut/typec_dut/typec_rx_dut/state[0]} {tb_typec_dut/typec_dut/typec_rx_dut/state[1]} {tb_typec_dut/typec_dut/typec_rx_dut/state[2]} {tb_typec_dut/typec_dut/typec_rx_dut/state[3]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {tb_typec_dut/typec_dut/typec_cs_dut/state[0]} {tb_typec_dut/typec_dut/typec_cs_dut/state[1]} {tb_typec_dut/typec_dut/typec_cs_dut/state[2]} {tb_typec_dut/typec_dut/typec_cs_dut/state[3]} {tb_typec_dut/typec_dut/typec_cs_dut/state[4]} {tb_typec_dut/typec_dut/typec_cs_dut/state[5]} {tb_typec_dut/typec_dut/typec_cs_dut/state[6]} {tb_typec_dut/typec_dut/typec_cs_dut/state[7]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {tb_typec_dut/typec_dut/com_rxd[0]} {tb_typec_dut/typec_dut/com_rxd[1]} {tb_typec_dut/typec_dut/com_rxd[2]} {tb_typec_dut/typec_dut/com_rxd[3]} {tb_typec_dut/typec_dut/com_rxd[4]} {tb_typec_dut/typec_dut/com_rxd[5]} {tb_typec_dut/typec_dut/com_rxd[6]} {tb_typec_dut/typec_dut/com_rxd[7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {tb_typec_dut/typec_dut/com_txd[0]} {tb_typec_dut/typec_dut/com_txd[1]} {tb_typec_dut/typec_dut/com_txd[2]} {tb_typec_dut/typec_dut/com_txd[3]} {tb_typec_dut/typec_dut/com_txd[4]} {tb_typec_dut/typec_dut/com_txd[5]} {tb_typec_dut/typec_dut/com_txd[6]} {tb_typec_dut/typec_dut/com_txd[7]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {tb_typec_dut/typec_dut/tx_btype[0]} {tb_typec_dut/typec_dut/tx_btype[1]} {tb_typec_dut/typec_dut/tx_btype[2]} {tb_typec_dut/typec_dut/tx_btype[3]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {tb_typec_dut/typec_dut/rx_btype[0]} {tb_typec_dut/typec_dut/rx_btype[1]} {tb_typec_dut/typec_dut/rx_btype[2]} {tb_typec_dut/typec_dut/rx_btype[3]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {tb_typec_dut/typecm_dut/typecm_cs_dut/state[0]} {tb_typec_dut/typecm_dut/typecm_cs_dut/state[1]} {tb_typec_dut/typecm_dut/typecm_cs_dut/state[2]} {tb_typec_dut/typecm_dut/typecm_cs_dut/state[3]} {tb_typec_dut/typecm_dut/typecm_cs_dut/state[4]} {tb_typec_dut/typecm_dut/typecm_cs_dut/state[5]} {tb_typec_dut/typecm_dut/typecm_cs_dut/state[6]} {tb_typec_dut/typecm_dut/typecm_cs_dut/state[7]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {tb_typec_dut/s_send_btype[0]} {tb_typec_dut/s_send_btype[1]} {tb_typec_dut/s_send_btype[2]} {tb_typec_dut/s_send_btype[3]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {tb_typec_dut/s_read_btype[0]} {tb_typec_dut/s_read_btype[1]} {tb_typec_dut/s_read_btype[2]} {tb_typec_dut/s_read_btype[3]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {tb_typec_dut/m_read_bdata[0]} {tb_typec_dut/m_read_bdata[1]} {tb_typec_dut/m_read_bdata[2]} {tb_typec_dut/m_read_bdata[3]} {tb_typec_dut/m_read_bdata[4]} {tb_typec_dut/m_read_bdata[5]} {tb_typec_dut/m_read_bdata[6]} {tb_typec_dut/m_read_bdata[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {tb_typec_dut/state[0]} {tb_typec_dut/state[1]} {tb_typec_dut/state[2]} {tb_typec_dut/state[3]} {tb_typec_dut/state[4]} {tb_typec_dut/state[5]} {tb_typec_dut/state[6]} {tb_typec_dut/state[7]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {tb_typec_dut/pm_rxd[0]} {tb_typec_dut/pm_rxd[1]} {tb_typec_dut/pm_rxd[2]} {tb_typec_dut/pm_rxd[3]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {tb_typec_dut/m_read_btype[0]} {tb_typec_dut/m_read_btype[1]} {tb_typec_dut/m_read_btype[2]} {tb_typec_dut/m_read_btype[3]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {tb_typec_dut/ps_txd[0]} {tb_typec_dut/ps_txd[1]} {tb_typec_dut/ps_txd[2]} {tb_typec_dut/ps_txd[3]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {tb_typec_dut/m_send_btype[0]} {tb_typec_dut/m_send_btype[1]} {tb_typec_dut/m_send_btype[2]} {tb_typec_dut/m_send_btype[3]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {tb_typec_dut/s_read_bdata[0]} {tb_typec_dut/s_read_bdata[1]} {tb_typec_dut/s_read_bdata[2]} {tb_typec_dut/s_read_bdata[3]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list tb_typec_dut/typec_dut/fd_rx]]
connect_debug_port u_ila_0/probe17 [get_nets [list tb_typec_dut/typec_dut/fd_tx]]
connect_debug_port u_ila_0/probe18 [get_nets [list tb_typec_dut/fdm_read]]
connect_debug_port u_ila_0/probe19 [get_nets [list tb_typec_dut/fdm_send]]
connect_debug_port u_ila_0/probe20 [get_nets [list tb_typec_dut/fds_read]]
connect_debug_port u_ila_0/probe21 [get_nets [list tb_typec_dut/fds_send]]
connect_debug_port u_ila_0/probe22 [get_nets [list tb_typec_dut/fm_recv]]
connect_debug_port u_ila_0/probe23 [get_nets [list tb_typec_dut/fm_send]]
connect_debug_port u_ila_0/probe24 [get_nets [list tb_typec_dut/fs_recv]]
connect_debug_port u_ila_0/probe25 [get_nets [list tb_typec_dut/typec_dut/fs_rx]]
connect_debug_port u_ila_0/probe26 [get_nets [list tb_typec_dut/fs_send]]
connect_debug_port u_ila_0/probe27 [get_nets [list tb_typec_dut/typec_dut/fs_tx]]
connect_debug_port u_ila_0/probe28 [get_nets [list tb_typec_dut/fsm_read]]
connect_debug_port u_ila_0/probe29 [get_nets [list tb_typec_dut/fsm_send]]
connect_debug_port u_ila_0/probe30 [get_nets [list tb_typec_dut/fss_read]]
connect_debug_port u_ila_0/probe31 [get_nets [list tb_typec_dut/fss_send]]
connect_debug_port u_ila_0/probe32 [get_nets [list tb_typec_dut/pm_txd]]
connect_debug_port u_ila_0/probe33 [get_nets [list tb_typec_dut/ps_rxd]]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out3]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {tb_adc2ram_dut/state[0]} {tb_adc2ram_dut/state[1]} {tb_adc2ram_dut/state[2]} {tb_adc2ram_dut/state[3]} {tb_adc2ram_dut/state[4]} {tb_adc2ram_dut/state[5]} {tb_adc2ram_dut/state[6]} {tb_adc2ram_dut/state[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {tb_adc2ram_dut/fifo_rxen[0]} {tb_adc2ram_dut/fifo_rxen[1]} {tb_adc2ram_dut/fifo_rxen[2]} {tb_adc2ram_dut/fifo_rxen[3]} {tb_adc2ram_dut/fifo_rxen[4]} {tb_adc2ram_dut/fifo_rxen[5]} {tb_adc2ram_dut/fifo_rxen[6]} {tb_adc2ram_dut/fifo_rxen[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {tb_adc2ram_dut/ram_tx_addr[0]} {tb_adc2ram_dut/ram_tx_addr[1]} {tb_adc2ram_dut/ram_tx_addr[2]} {tb_adc2ram_dut/ram_tx_addr[3]} {tb_adc2ram_dut/ram_tx_addr[4]} {tb_adc2ram_dut/ram_tx_addr[5]} {tb_adc2ram_dut/ram_tx_addr[6]} {tb_adc2ram_dut/ram_tx_addr[7]} {tb_adc2ram_dut/ram_tx_addr[8]} {tb_adc2ram_dut/ram_tx_addr[9]} {tb_adc2ram_dut/ram_tx_addr[10]} {tb_adc2ram_dut/ram_tx_addr[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 64 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {tb_adc2ram_dut/fifo_rxd[0]} {tb_adc2ram_dut/fifo_rxd[1]} {tb_adc2ram_dut/fifo_rxd[2]} {tb_adc2ram_dut/fifo_rxd[3]} {tb_adc2ram_dut/fifo_rxd[4]} {tb_adc2ram_dut/fifo_rxd[5]} {tb_adc2ram_dut/fifo_rxd[6]} {tb_adc2ram_dut/fifo_rxd[7]} {tb_adc2ram_dut/fifo_rxd[8]} {tb_adc2ram_dut/fifo_rxd[9]} {tb_adc2ram_dut/fifo_rxd[10]} {tb_adc2ram_dut/fifo_rxd[11]} {tb_adc2ram_dut/fifo_rxd[12]} {tb_adc2ram_dut/fifo_rxd[13]} {tb_adc2ram_dut/fifo_rxd[14]} {tb_adc2ram_dut/fifo_rxd[15]} {tb_adc2ram_dut/fifo_rxd[16]} {tb_adc2ram_dut/fifo_rxd[17]} {tb_adc2ram_dut/fifo_rxd[18]} {tb_adc2ram_dut/fifo_rxd[19]} {tb_adc2ram_dut/fifo_rxd[20]} {tb_adc2ram_dut/fifo_rxd[21]} {tb_adc2ram_dut/fifo_rxd[22]} {tb_adc2ram_dut/fifo_rxd[23]} {tb_adc2ram_dut/fifo_rxd[24]} {tb_adc2ram_dut/fifo_rxd[25]} {tb_adc2ram_dut/fifo_rxd[26]} {tb_adc2ram_dut/fifo_rxd[27]} {tb_adc2ram_dut/fifo_rxd[28]} {tb_adc2ram_dut/fifo_rxd[29]} {tb_adc2ram_dut/fifo_rxd[30]} {tb_adc2ram_dut/fifo_rxd[31]} {tb_adc2ram_dut/fifo_rxd[32]} {tb_adc2ram_dut/fifo_rxd[33]} {tb_adc2ram_dut/fifo_rxd[34]} {tb_adc2ram_dut/fifo_rxd[35]} {tb_adc2ram_dut/fifo_rxd[36]} {tb_adc2ram_dut/fifo_rxd[37]} {tb_adc2ram_dut/fifo_rxd[38]} {tb_adc2ram_dut/fifo_rxd[39]} {tb_adc2ram_dut/fifo_rxd[40]} {tb_adc2ram_dut/fifo_rxd[41]} {tb_adc2ram_dut/fifo_rxd[42]} {tb_adc2ram_dut/fifo_rxd[43]} {tb_adc2ram_dut/fifo_rxd[44]} {tb_adc2ram_dut/fifo_rxd[45]} {tb_adc2ram_dut/fifo_rxd[46]} {tb_adc2ram_dut/fifo_rxd[47]} {tb_adc2ram_dut/fifo_rxd[48]} {tb_adc2ram_dut/fifo_rxd[49]} {tb_adc2ram_dut/fifo_rxd[50]} {tb_adc2ram_dut/fifo_rxd[51]} {tb_adc2ram_dut/fifo_rxd[52]} {tb_adc2ram_dut/fifo_rxd[53]} {tb_adc2ram_dut/fifo_rxd[54]} {tb_adc2ram_dut/fifo_rxd[55]} {tb_adc2ram_dut/fifo_rxd[56]} {tb_adc2ram_dut/fifo_rxd[57]} {tb_adc2ram_dut/fifo_rxd[58]} {tb_adc2ram_dut/fifo_rxd[59]} {tb_adc2ram_dut/fifo_rxd[60]} {tb_adc2ram_dut/fifo_rxd[61]} {tb_adc2ram_dut/fifo_rxd[62]} {tb_adc2ram_dut/fifo_rxd[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {tb_adc2ram_dut/fifo_txd[0]} {tb_adc2ram_dut/fifo_txd[1]} {tb_adc2ram_dut/fifo_txd[2]} {tb_adc2ram_dut/fifo_txd[3]} {tb_adc2ram_dut/fifo_txd[4]} {tb_adc2ram_dut/fifo_txd[5]} {tb_adc2ram_dut/fifo_txd[6]} {tb_adc2ram_dut/fifo_txd[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {tb_adc2ram_dut/ram_rxd[0]} {tb_adc2ram_dut/ram_rxd[1]} {tb_adc2ram_dut/ram_rxd[2]} {tb_adc2ram_dut/ram_rxd[3]} {tb_adc2ram_dut/ram_rxd[4]} {tb_adc2ram_dut/ram_rxd[5]} {tb_adc2ram_dut/ram_rxd[6]} {tb_adc2ram_dut/ram_rxd[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {tb_adc2ram_dut/ram_txd[0]} {tb_adc2ram_dut/ram_txd[1]} {tb_adc2ram_dut/ram_txd[2]} {tb_adc2ram_dut/ram_txd[3]} {tb_adc2ram_dut/ram_txd[4]} {tb_adc2ram_dut/ram_txd[5]} {tb_adc2ram_dut/ram_txd[6]} {tb_adc2ram_dut/ram_txd[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 12 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {tb_adc2ram_dut/ram_rx_addr[0]} {tb_adc2ram_dut/ram_rx_addr[1]} {tb_adc2ram_dut/ram_rx_addr[2]} {tb_adc2ram_dut/ram_rx_addr[3]} {tb_adc2ram_dut/ram_rx_addr[4]} {tb_adc2ram_dut/ram_rx_addr[5]} {tb_adc2ram_dut/ram_rx_addr[6]} {tb_adc2ram_dut/ram_rx_addr[7]} {tb_adc2ram_dut/ram_rx_addr[8]} {tb_adc2ram_dut/ram_rx_addr[9]} {tb_adc2ram_dut/ram_rx_addr[10]} {tb_adc2ram_dut/ram_rx_addr[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list tb_adc2ram_dut/fd_fifo_tx]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list tb_adc2ram_dut/fd_ram_rx]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list tb_adc2ram_dut/fd_tran]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list tb_adc2ram_dut/fifo_txen]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list tb_adc2ram_dut/fs_fifo_tx]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list tb_adc2ram_dut/fs_ram_rx]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list tb_adc2ram_dut/fs_tran]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list tb_adc2ram_dut/ram_txen]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
