create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {tb_udp_tx_dut/fifo_rxd[0]} {tb_udp_tx_dut/fifo_rxd[1]} {tb_udp_tx_dut/fifo_rxd[2]} {tb_udp_tx_dut/fifo_rxd[3]} {tb_udp_tx_dut/fifo_rxd[4]} {tb_udp_tx_dut/fifo_rxd[5]} {tb_udp_tx_dut/fifo_rxd[6]} {tb_udp_tx_dut/fifo_rxd[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {tb_udp_tx_dut/udp_tx_dut/state[0]} {tb_udp_tx_dut/udp_tx_dut/state[1]} {tb_udp_tx_dut/udp_tx_dut/state[2]} {tb_udp_tx_dut/udp_tx_dut/state[3]} {tb_udp_tx_dut/udp_tx_dut/state[4]} {tb_udp_tx_dut/udp_tx_dut/state[5]} {tb_udp_tx_dut/udp_tx_dut/state[6]} {tb_udp_tx_dut/udp_tx_dut/state[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {tb_udp_tx_dut/fifo_txd[0]} {tb_udp_tx_dut/fifo_txd[1]} {tb_udp_tx_dut/fifo_txd[2]} {tb_udp_tx_dut/fifo_txd[3]} {tb_udp_tx_dut/fifo_txd[4]} {tb_udp_tx_dut/fifo_txd[5]} {tb_udp_tx_dut/fifo_txd[6]} {tb_udp_tx_dut/fifo_txd[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {tb_udp_tx_dut/state[0]} {tb_udp_tx_dut/state[1]} {tb_udp_tx_dut/state[2]} {tb_udp_tx_dut/state[3]} {tb_udp_tx_dut/state[4]} {tb_udp_tx_dut/state[5]} {tb_udp_tx_dut/state[6]} {tb_udp_tx_dut/state[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list tb_udp_tx_dut/fifo_full]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list tb_udp_tx_dut/fifo_rxen]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list tb_udp_tx_dut/fifo_txen]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
