connect_debug_port u_ila_0/probe3 [get_nets [list {com_dut/eth_dut/mac_test0/tx_state[0]} {com_dut/eth_dut/mac_test0/tx_state[1]} {com_dut/eth_dut/mac_test0/tx_state[2]} {com_dut/eth_dut/mac_test0/tx_state[3]} {com_dut/eth_dut/mac_test0/tx_state[4]} {com_dut/eth_dut/mac_test0/tx_state[5]} {com_dut/eth_dut/mac_test0/tx_state[6]}]]


connect_debug_port u_ila_0/probe1 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/ip0/state[0]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/ip0/state[1]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/ip0/state[2]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/ip0/state[3]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/ip0/state[4]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/ip0/state[5]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/ip0/state[6]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/state[0]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/state[1]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/state[2]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/state[3]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/state[4]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/state[5]}]]

connect_debug_port u_ila_0/probe0 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[0]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[1]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[2]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[3]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[4]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[5]}]]



connect_debug_port u_ila_0/probe0 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[0]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[1]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[2]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[3]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[4]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[5]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[6]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[7]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[8]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[9]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[10]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[11]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[12]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[13]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[14]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[15]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[0]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[1]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[2]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[3]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[4]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[5]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[0]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[1]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[2]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[3]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[4]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[5]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[6]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[7]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[8]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[9]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[10]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[11]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[12]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[13]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[14]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[15]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {com_dut/eth_dut/mac_test0/tx_state[0]} {com_dut/eth_dut/mac_test0/tx_state[1]} {com_dut/eth_dut/mac_test0/tx_state[2]} {com_dut/eth_dut/mac_test0/tx_state[3]} {com_dut/eth_dut/mac_test0/tx_state[4]} {com_dut/eth_dut/mac_test0/tx_state[5]} {com_dut/eth_dut/mac_test0/tx_state[6]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {com_dut/eth_dut/mac_test0/nosend_len[0]} {com_dut/eth_dut/mac_test0/nosend_len[1]} {com_dut/eth_dut/mac_test0/nosend_len[2]} {com_dut/eth_dut/mac_test0/nosend_len[3]} {com_dut/eth_dut/mac_test0/nosend_len[4]} {com_dut/eth_dut/mac_test0/nosend_len[5]} {com_dut/eth_dut/mac_test0/nosend_len[6]} {com_dut/eth_dut/mac_test0/nosend_len[7]} {com_dut/eth_dut/mac_test0/nosend_len[8]} {com_dut/eth_dut/mac_test0/nosend_len[9]} {com_dut/eth_dut/mac_test0/nosend_len[10]} {com_dut/eth_dut/mac_test0/nosend_len[11]} {com_dut/eth_dut/mac_test0/nosend_len[12]} {com_dut/eth_dut/mac_test0/nosend_len[13]} {com_dut/eth_dut/mac_test0/nosend_len[14]} {com_dut/eth_dut/mac_test0/nosend_len[15]}]]

connect_debug_port u_ila_0/probe3 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[0]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[1]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[2]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[3]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[4]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[5]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[6]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[7]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[8]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[9]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[10]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[11]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[12]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[13]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[14]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_cnt[15]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[0]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[1]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[2]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[3]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[4]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[5]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[6]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[7]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[8]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[9]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[10]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[11]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[12]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[13]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[14]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/checksum_udp_len[15]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[0]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[1]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[2]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[3]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[4]} {com_dut/eth_dut/mac_test0/mac_top0/mac_tx0/udp0/ck_state[5]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {com_dut/eth_dut/mac_test0/noSend_len[0]} {com_dut/eth_dut/mac_test0/noSend_len[1]} {com_dut/eth_dut/mac_test0/noSend_len[2]} {com_dut/eth_dut/mac_test0/noSend_len[3]} {com_dut/eth_dut/mac_test0/noSend_len[4]} {com_dut/eth_dut/mac_test0/noSend_len[5]} {com_dut/eth_dut/mac_test0/noSend_len[6]} {com_dut/eth_dut/mac_test0/noSend_len[7]} {com_dut/eth_dut/mac_test0/noSend_len[8]} {com_dut/eth_dut/mac_test0/noSend_len[9]} {com_dut/eth_dut/mac_test0/noSend_len[10]} {com_dut/eth_dut/mac_test0/noSend_len[11]} {com_dut/eth_dut/mac_test0/noSend_len[12]} {com_dut/eth_dut/mac_test0/noSend_len[13]} {com_dut/eth_dut/mac_test0/noSend_len[14]} {com_dut/eth_dut/mac_test0/noSend_len[15]}]]


connect_debug_port u_ila_0/probe2 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[0]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[1]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[2]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[3]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[4]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/ck_state[5]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {com_dut/eth_dut/mac_test0/nosend_len[0]} {com_dut/eth_dut/mac_test0/nosend_len[1]} {com_dut/eth_dut/mac_test0/nosend_len[2]} {com_dut/eth_dut/mac_test0/nosend_len[3]} {com_dut/eth_dut/mac_test0/nosend_len[4]} {com_dut/eth_dut/mac_test0/nosend_len[5]} {com_dut/eth_dut/mac_test0/nosend_len[6]} {com_dut/eth_dut/mac_test0/nosend_len[7]} {com_dut/eth_dut/mac_test0/nosend_len[8]} {com_dut/eth_dut/mac_test0/nosend_len[9]} {com_dut/eth_dut/mac_test0/nosend_len[10]} {com_dut/eth_dut/mac_test0/nosend_len[11]} {com_dut/eth_dut/mac_test0/nosend_len[12]} {com_dut/eth_dut/mac_test0/nosend_len[13]} {com_dut/eth_dut/mac_test0/nosend_len[14]} {com_dut/eth_dut/mac_test0/nosend_len[15]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list com_dut/eth_dut/mac_test0/last_pkg]]
connect_debug_port u_ila_0/probe15 [get_nets [list com_dut/eth_dut/mac_test0/udp_ram_data_req]]
connect_debug_port u_ila_0/probe17 [get_nets [list com_dut/eth_dut/mac_test0/udp_tx_end]]
connect_debug_port u_ila_0/probe18 [get_nets [list com_dut/eth_dut/mac_test0/udp_tx_req]]

connect_debug_port u_ila_0/probe2 [get_nets [list {com_dut/eth_dut/mac_test0/gmii_txd[0]} {com_dut/eth_dut/mac_test0/gmii_txd[1]} {com_dut/eth_dut/mac_test0/gmii_txd[2]} {com_dut/eth_dut/mac_test0/gmii_txd[3]} {com_dut/eth_dut/mac_test0/gmii_txd[4]} {com_dut/eth_dut/mac_test0/gmii_txd[5]} {com_dut/eth_dut/mac_test0/gmii_txd[6]} {com_dut/eth_dut/mac_test0/gmii_txd[7]}]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list e_grxc_g]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {com_dut/com_read_dut/btype[0]} {com_dut/com_read_dut/btype[1]} {com_dut/com_read_dut/btype[2]} {com_dut/com_read_dut/btype[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {com_dut/com_cs_dut/data_idx[0]} {com_dut/com_cs_dut/data_idx[1]} {com_dut/com_cs_dut/data_idx[2]} {com_dut/com_cs_dut/data_idx[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[0]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[1]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[2]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[3]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[4]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[5]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[6]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[7]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[8]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[9]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[10]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[11]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[12]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[13]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[14]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_cnt[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[0]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[1]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[2]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[3]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[4]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[5]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[6]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[7]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[8]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[9]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[10]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[11]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[12]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[13]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[14]} {com_dut/eth_dut/mac_test0/mac_top_dut/mac_tx0/udp0/checksum_udp_len[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 13 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {com_dut/ram_data_dlen[0]} {com_dut/ram_data_dlen[1]} {com_dut/ram_data_dlen[2]} {com_dut/ram_data_dlen[3]} {com_dut/ram_data_dlen[4]} {com_dut/ram_data_dlen[5]} {com_dut/ram_data_dlen[6]} {com_dut/ram_data_dlen[7]} {com_dut/ram_data_dlen[8]} {com_dut/ram_data_dlen[9]} {com_dut/ram_data_dlen[10]} {com_dut/ram_data_dlen[11]} {com_dut/ram_data_dlen[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list com_dut/fd_eth_send]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list com_dut/fs_eth_send]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_norm]
